# Generated by Django 2.2.1 on 2019-05-05 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_galleryimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallerysubpage',
            name='date',
        ),
    ]
